modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="Apache License 2.0"
issueTrackerURL="https://github.com/satxm/mcwifipnp/issues"
clientSideOnly=true

[[mods]]
modId="mcwifipnp"
version="${mod_version}"
displayName="LAN World Plug-n-Play"
#updateJSONURL=""
displayURL="https://github.com/satxm/mcwifipnp"
logoFile="mcwifipnp.png"
authors="Satxm"
description="A Minecraft LAN World Tool With WLAN UPnP."

[[dependencies.mcwifipnp]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.mcwifipnp]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
